[[libpolars]]
arch = "aarch64"
git-tree-sha1 = "5183ce30312d6c36f3d3bec8fd220afd6067c495"
os = "macos"

    [[libpolars.download]]
    sha256 = "0969c6e54c081e8c0ce7e9ff4bd59c607ec2dc9c5e0c4a06e620d62e64d1af22"
    url = "https://github.com/JuliaBinaryWrappers/libpolars_jll.jl/releases/download/libpolars-v0.1.1+0/libpolars.v0.1.1.aarch64-apple-darwin.tar.gz"
[[libpolars]]
arch = "aarch64"
git-tree-sha1 = "5a1c2b37c358ad49bf5b57a7971d773c127d3a38"
libc = "glibc"
os = "linux"

    [[libpolars.download]]
    sha256 = "689251a9a6eedcfb78d8e54b69d2205c7ec1fae17304bad442d66232c78463bc"
    url = "https://github.com/JuliaBinaryWrappers/libpolars_jll.jl/releases/download/libpolars-v0.1.1+0/libpolars.v0.1.1.aarch64-linux-gnu.tar.gz"
[[libpolars]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "39d487d92df0749ab746a977a02f01055154d5f0"
libc = "glibc"
os = "linux"

    [[libpolars.download]]
    sha256 = "ea9bc99313a9f6467ec4889b27520b1bf18e6cfbaa000313560a86c7d6c01b03"
    url = "https://github.com/JuliaBinaryWrappers/libpolars_jll.jl/releases/download/libpolars-v0.1.1+0/libpolars.v0.1.1.armv6l-linux-gnueabihf.tar.gz"
[[libpolars]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5ab7f482eeb947a3b850481ce4e4e94eaf32dfd8"
libc = "glibc"
os = "linux"

    [[libpolars.download]]
    sha256 = "b7416823af66c1cfa0739b41c696be85465e7ed3e10df3be406e72ac6c48376b"
    url = "https://github.com/JuliaBinaryWrappers/libpolars_jll.jl/releases/download/libpolars-v0.1.1+0/libpolars.v0.1.1.armv7l-linux-gnueabihf.tar.gz"
[[libpolars]]
arch = "i686"
git-tree-sha1 = "f3ccf4bca5a98b1192564bb9338a11c1139f4df2"
libc = "glibc"
os = "linux"

    [[libpolars.download]]
    sha256 = "f8fb8b0468b8bc1da5de395c22447a9eb62a9ecad9b7b96e32bd9e1bc384e619"
    url = "https://github.com/JuliaBinaryWrappers/libpolars_jll.jl/releases/download/libpolars-v0.1.1+0/libpolars.v0.1.1.i686-linux-gnu.tar.gz"
[[libpolars]]
arch = "powerpc64le"
git-tree-sha1 = "1c1b8159a561b25cc9da0e4e5e1d45ff63f2dbd0"
libc = "glibc"
os = "linux"

    [[libpolars.download]]
    sha256 = "36d2ee86473ea20d8b86b67ec050f6285d0a96e3f4a4eb96e6589a2bbc2c1a0c"
    url = "https://github.com/JuliaBinaryWrappers/libpolars_jll.jl/releases/download/libpolars-v0.1.1+0/libpolars.v0.1.1.powerpc64le-linux-gnu.tar.gz"
[[libpolars]]
arch = "x86_64"
git-tree-sha1 = "aef9e1dfed52d93fc60439f25be70deb5d424600"
os = "macos"

    [[libpolars.download]]
    sha256 = "ec5987aa57813c19a805a558bdad0a37aace63bd51cff98261e4b28fe0148759"
    url = "https://github.com/JuliaBinaryWrappers/libpolars_jll.jl/releases/download/libpolars-v0.1.1+0/libpolars.v0.1.1.x86_64-apple-darwin.tar.gz"
[[libpolars]]
arch = "x86_64"
git-tree-sha1 = "5bcefb826b9dd410e35355ee7ce08f216897f651"
libc = "glibc"
os = "linux"

    [[libpolars.download]]
    sha256 = "98339ebfdf555df4a9f0c8a04134d099033ed2c792baa493551b5a64afca2ea4"
    url = "https://github.com/JuliaBinaryWrappers/libpolars_jll.jl/releases/download/libpolars-v0.1.1+0/libpolars.v0.1.1.x86_64-linux-gnu.tar.gz"
[[libpolars]]
arch = "x86_64"
git-tree-sha1 = "90b60a84efb3f992024342cb6b43704c9e941d37"
os = "freebsd"

    [[libpolars.download]]
    sha256 = "793047d664db230cb0575ff5015e38ca354a2a4097d366558be2f7d43eaec26d"
    url = "https://github.com/JuliaBinaryWrappers/libpolars_jll.jl/releases/download/libpolars-v0.1.1+0/libpolars.v0.1.1.x86_64-unknown-freebsd.tar.gz"
[[libpolars]]
arch = "x86_64"
git-tree-sha1 = "76b814e622f95aaf3e0b84596bcb9cd9f7a6d4ca"
os = "windows"

    [[libpolars.download]]
    sha256 = "c4db623d4d0b2792ca7eab11b6332ab673b87758c33cf7a30d42f878db0b74c3"
    url = "https://github.com/JuliaBinaryWrappers/libpolars_jll.jl/releases/download/libpolars-v0.1.1+0/libpolars.v0.1.1.x86_64-w64-mingw32.tar.gz"
