# Autogenerated wrapper script for libpolars_jll for x86_64-w64-mingw32
export libpolars

JLLWrappers.@generate_wrapper_header("libpolars")
JLLWrappers.@declare_library_product(libpolars, "libpolars.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libpolars,
        "bin\\libpolars.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
